version: "3"
services:
  backend:
    build: .
    ports:
      - "8000:8080"
    depends_on:
      - database

  database:
    image: postgres:13.1
    environment:
      - POSTGRES_PASSWORD=skniskni
      - POSTGRES_USER=skni
      - POSTGRES_DB=skni
